name: smart_home_iot
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.3
  jwt_decode: ^0.3.1
  another_flushbar: ^1.12.30
  intl: ^0.19.0
  lottie: ^3.1.2 # Kiểm tra phiên bản mới nhất trên pub.dev
  # 🔹 BIOMETRIC AUTH (Vân tay / Khuôn mặt điện thoại)
  local_auth: ^2.3.0

  # 🔹 VOICE RECORDING (Phục vụ Voice Control từ File 2)
  record: ^6.2.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
